## Overview

This Jupyter notebook makes it easy to :

1. Get the dataset and column metadata programmatically
2. Load CSV files automatically into a pandas dataframe so you can do the fun explorations

# Setup
1. Paste the dataset ID you copied into the cell below
2. Run All Cells (click `Runtime` -> `Run All`)

In [5]:
DATASET_ID = "d_8b84c4ee58e3cfc0ece0d773c8ca6abc" # e.g. "d_69b3380ad7e51aff3a7dcc84eba52b8a"
API_KEY = "PASTE_API_KEY_HERE" #e.g. "v2:a7ae10..."

## Dataset and Column Metadata

In [6]:
import json
import requests

s = requests.Session()
s.headers.update({'referer': 'https://colab.research.google.com'})
if API_KEY and API_KEY != "PASTE_API_KEY_HERE":
    s.headers['x-api-key'] = API_KEY
s.headers.update(s.headers)
base_url = "https://api-production.data.gov.sg"
url = base_url + f"/v2/public/api/datasets/{DATASET_ID}/metadata"
print(url)
response = s.get(url)
data = response.json()['data']
columnMetadata = data.pop('columnMetadata', None)

print("Dataset Metadata:")
print(json.dumps(data, indent=2))

print("\nColumns:\n", list(columnMetadata['map'].values()))

https://api-production.data.gov.sg/v2/public/api/datasets/d_8b84c4ee58e3cfc0ece0d773c8ca6abc/metadata
Dataset Metadata:
{
  "datasetId": "d_8b84c4ee58e3cfc0ece0d773c8ca6abc",
  "createdAt": "2021-07-28T10:37:00+08:00",
  "name": "Resale flat prices based on registration date from Jan-2017 onwards",
  "collectionIds": [
    "189"
  ],
  "description": "Notes:\n\n1. The approximate floor area includes any recess area purchased, space adding item under HDB\u2019s upgrading programmes, roof terrace, etc.\n\n2. The transactions exclude resale transactions that may not reflect the full market price such as resale between relatives and resale of part shares.\n\n3. Resale prices should be taken as indicative only as the resale prices agreed between buyers and sellers are dependent on many factors.",
  "format": "CSV",
  "lastUpdatedAt": "2026-10-12T02:10:19+08:00",
  "managedBy": "Housing & Development Board",
  "coverageStart": "2017-01-01T08:00:00+08:00",
  "coverageEnd": "2026-10-01T08:00:00+08:00",
  "contactEmails": [
    "lau_pei_wen@hdb.gov.sg"
  ],
  "datasetSize": 23983413
}

Columns:
 ['month', 'town', 'flat_type', 'block', 'street_name', 'storey_range', 'floor_area_sqm', 'flat_model', 'lease_commence_date', 'remaining_lease', 'resale_price']

## Download File

In [7]:
import time
import pandas as pd

def download_file(DATASET_ID, API_KEY=None):

  headers = {"Content-Type": "application/json"}
  if API_KEY:
      headers["x-api-key"] = API_KEY
  # initiate download
  initiate_download_response = s.get(
      f"https://api-open.data.gov.sg/v1/public/api/datasets/{DATASET_ID}/initiate-download",
      headers=headers,
      json={}
  )
  print(initiate_download_response.json()['data']['message'])

  # poll download
  MAX_POLLS = 5
  for i in range(MAX_POLLS):
    poll_download_response = s.get(
        f"https://api-open.data.gov.sg/v1/public/api/datasets/{DATASET_ID}/poll-download",
        headers=headers,
        json={}
    )
    print("Poll download response:", poll_download_response.json())
    if "url" in poll_download_response.json()['data']:
      print(poll_download_response.json()['data']['url'])
      DOWNLOAD_URL = poll_download_response.json()['data']['url']
      df = pd.read_csv(DOWNLOAD_URL)

      display(df.head())
      print("\nDataframe loaded!")
      return df
    if i == MAX_POLLS - 1:
      print(f"{i+1}/{MAX_POLLS}: No result found, possible error with dataset, please try again or let us know at https://go.gov.sg/datagov-supportform\n")
    else:
      print(f"{i+1}/{MAX_POLLS}: No result yet, continuing to poll\n")
    time.sleep(3)

df = download_file(DATASET_ID)

Download successfully initiated. Proceed to poll download
Poll download response: {'code': 0, 'data': {'status': 'DOWNLOAD_SUCCESS', 'url': 'https://s3.ap-southeast-1.amazonaws.com/table-downloads-ingest.data.gov.sg/d_8b84c4ee58e3cfc0ece0d773c8ca6abc/6f8109f7bce05c219b3825a999cc7f3a02cbc19fe536138a5eaf86bfe6d8711f.csv?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=ASIAU7LWPY2WC5CFXUTT%2F20261012%2Fap-southeast-1%2Fs3%2Faws4_request&X-Amz-Date=20261012T121954Z&X-Amz-Expires=3600&X-Amz-Security-Token=IQoJb3JpZ2luX2VjELj%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEaDmFwLXNvdXRoZWFzdC0xIkYwRAIgFhgHFuXPmdGEXiEVMrNPUp1RWEfw3Te45pQ8jQguJvMCIBy%2BMvvonYMrNDuP8jCI%2FGpAx%2FpsiQz6jbt1jhnsDRmEKosECIH%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEQBBoMMzQyMjM1MjY4NzgwIgxhcqj6jtdB1fmPVtIq3wPDTZOVRP9t3JqwB3KfoCTvWOIoIy12B1507stOUTUiEDYku4tcMRJf9h%2FDu6RkzHtlTHSz8Kstznul9F%2B3q9kyqM2wPmsx2uHaMJDRD3tq7BwRsOvAElUbeWI6Zm0Gp9JR5tZqeRRUfzOAYlEYvjpUBPM%2BdoO%2F2bOfDf%2B2J5%2FKXyJ0u%2BmpUGgTtIQLhmkWtmELaK0fgO76E%2B5KTYyizcbcgmER9FhwO3zc4AQ6fz8UhBeC0Bdjk7AGn1YV68BUzPxO0Ogr%2BAb0zIg3NfK%2BVCAED6vjsuDbwESHHRTGCkKalh0%2BCdAl5hN3rTTHd6ObaVA%2FA5ZcPPfAf11kSRnTl1UlRIhn7DwyNelbBPX%2FkpsNCs8QMfztwV3lVvCvW6pNzVLnByDdq3vu5VJzi5fv64yWjPOVRfnD0K5fzGQ1q%2FJ7TLRrjSigMo2yec6H4Mqww8TvbqbmjmvkQoEOZ%2FUnKG17GbYhqJY3pxbxrJyv%2BQr7dKM9USOGp71vAU%2BdtujAipLcwO4ZPEv0j8D19IKwbqm4JuX%2FQA7m4SR%2FDWfgNTa19YJ5JEYbrfkysq%2BLJ0B%2FIL03bY8dWIj8LHr%2F2%2FQakag%2BEyVW1l%2BYA8en%2Bjbar2vR90UOpKyZOtDbQ4g37UG07zCaqbLWBjqmARjY%2BlfeGZIlphVzlpZ29ZqTnFWC0gCLyG2gY7nQCQwna6oV0YXF8npB1J3M0aiXpgEy%2BOHJwx2fg6A1tMv0oAKD%2BkuqqezYu8UEVMPJRAd08M%2B7U%2FWLrfvkNOz%2B86x2xP8u9IBMptl2EDWsKBTSA6HuK1Kp5hadDe%2F%2BJgswgwCanFozuOr8PMSaGMMeLUiU%2BkBP6thKA494JRK7hf0nJcmTUIevX5c%3D&X-Amz-Signature=3052c69f6810618492da06d30ab99f0216542cffef40c7cbc147f20fbdf27a23&X-Amz-SignedHeaders=host&response-content-disposition=attachment%3B%20filename%3D%22ResaleflatpricesbasedonregistrationdatefromJan2017onwards.csv%22&x-amz-checksum-mode=ENABLED&x-id=GetObject'}, 'errorMsg': ''}
https://s3.ap-southeast-1.amazonaws.com/table-downloads-ingest.data.gov.sg/d_8b84c4ee58e3cfc0ece0d773c8ca6abc/6f8109f7bce05c219b3825a999cc7f3a02cbc19fe536138a5eaf86bfe6d8711f.csv?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=ASIAU7LWPY2WC5CFXUTT%2F20261012%2Fap-southeast-1%2Fs3%2Faws4_request&X-Amz-Date=20261012T121954Z&X-Amz-Expires=3600&X-Amz-Security-Token=IQoJb3JpZ2luX2VjELj%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEaDmFwLXNvdXRoZWFzdC0xIkYwRAIgFhgHFuXPmdGEXiEVMrNPUp1RWEfw3Te45pQ8jQguJvMCIBy%2BMvvonYMrNDuP8jCI%2FGpAx%2FpsiQz6jbt1jhnsDRmEKosECIH%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEQBBoMMzQyMjM1MjY4NzgwIgxhcqj6jtdB1fmPVtIq3wPDTZOVRP9t3JqwB3KfoCTvWOIoIy12B1507stOUTUiEDYku4tcMRJf9h%2FDu6RkzHtlTHSz8Kstznul9F%2B3q9kyqM2wPmsx2uHaMJDRD3tq7BwRsOvAElUbeWI6Zm0Gp9JR5tZqeRRUfzOAYlEYvjpUBPM%2BdoO%2F2bOfDf%2B2J5%2FKXyJ0u%2BmpUGgTtIQLhmkWtmELaK0fgO76E%2B5KTYyizcbcgmER9FhwO3zc4AQ6fz8UhBeC0Bdjk7AGn1YV68BUzPxO0Ogr%2BAb0zIg3NfK%2BVCAED6vjsuDbwESHHRTGCkKalh0%2BCdAl5hN3rTTHd6ObaVA%2FA5ZcPPfAf11kSRnTl1UlRIhn7DwyNelbBPX%2FkpsNCs8QMfztwV3lVvCvW6pNzVLnByDdq3vu5VJzi5fv64yWjPOVRfnD0K5fzGQ1q%2FJ7TLRrjSigMo2yec6H4Mqww8TvbqbmjmvkQoEOZ%2FUnKG17GbYhqJY3pxbxrJyv%2BQr7dKM9USOGp71vAU%2BdtujAipLcwO4ZPEv0j8D19IKwbqm4JuX%2FQA7m4SR%2FDWfgNTa19YJ5JEYbrfkysq%2BLJ0B%2FIL03bY8dWIj8LHr%2F2%2FQakag%2BEyVW1l%2BYA8en%2Bjbar2vR90UOpKyZOtDbQ4g37UG07zCaqbLWBjqmARjY%2BlfeGZIlphVzlpZ29ZqTnFWC0gCLyG2gY7nQCQwna6oV0YXF8npB1J3M0aiXpgEy%2BOHJwx2fg6A1tMv0oAKD%2BkuqqezYu8UEVMPJRAd08M%2B7U%2FWLrfvkNOz%2B86x2xP8u9IBMptl2EDWsKBTSA6HuK1Kp5hadDe%2F%2BJgswgwCanFozuOr8PMSaGMMeLUiU%2BkBP6thKA494JRK7hf0nJcmTUIevX5c%3D&X-Amz-Signature=3052c69f6810618492da06d30ab99f0216542cffef40c7cbc147f20fbdf27a23&X-Amz-SignedHeaders=host&response-content-disposition=attachment%3B%20filename%3D%22ResaleflatpricesbasedonregistrationdatefromJan2017onwards.csv%22&x-amz-checksum-mode=ENABLED&x-id=GetObject

,month,town,flat_type,block,street_name,storey_range,floor_area_sqm,flat_model,lease_commence_date,remaining_lease,resale_price
0,2017-01,ANG MO KIO,2 ROOM,406,ANG MO KIO AVE 10,10 TO 12,44.0,Improved,1979,61 years 04 months,232000.0
1,2017-01,ANG MO KIO,3 ROOM,108,ANG MO KIO AVE 4,01 TO 03,67.0,New Generation,1978,60 years 07 months,250000.0
2,2017-01,ANG MO KIO,3 ROOM,602,ANG MO KIO AVE 5,01 TO 03,67.0,New Generation,1980,62 years 05 months,262000.0
3,2017-01,ANG MO KIO,3 ROOM,465,ANG MO KIO AVE 10,04 TO 06,68.0,New Generation,1980,62 years 01 month,265000.0
4,2017-01,ANG MO KIO,3 ROOM,601,ANG MO KIO AVE 5,01 TO 03,67.0,New Generation,1980,62 years 05 months,265000.0

Dataframe loaded!

In [8]:
df.describe()

       floor_area_sqm  lease_commence_date  resale_price
count   242454.000000        242454.000000  2.424540e+05
mean        96.713011          1996.630322  5.363292e+05
std         24.023347            14.400655  1.933703e+05
min         31.000000          1966.000000  1.400000e+05
25%         81.000000          1985.000000  3.920000e+05
50%         93.000000          1997.000000  5.050000e+05
75%        112.000000          2012.000000  6.450000e+05
max        366.700000          2023.000000  1.728000e+06